### ISSUE TITLE
add --hostname parameter to avoid random hostname

### ISSUE THREAD

**Issue by winkler-winsen** [piwi3910/techtalk#5]
When using no `--hostname` parameter in `docker run`, the hostname becomes a random numer and is not easyly changeable after creating container.

Please put a line into `docker run` parameters in https://github.com/piwi3910/techtalk/tree/master/Docker_series/07#starting-pi-hole

e.g.
`           --hostname "pihole" \
`

Thanks in advance.
Lars

**Comment by piwi3910** [comment]
Thank you 👍
